Week3
arnavss2/my-portfolio pull request #4
Opened 2022-06-20 00:10 UTC by arnavss2

Add some styling for UI
Add variables for constants

2022-06-20 00:45 UTC, dchickabasapa requested changes
Would like another iteration as there is a logical mistake. 

Also remove an empty file in the change.

2022-06-20 00:45 UTC, dchickabasapa commented on portfolio/src/main/java/com/google/sps/servlets/Contact.java
> +    public Contact(long set_id, String set_name, String set_email, String set_message){
Have this code as:

public Contact(long id, String name, String email, String message) {
  this.id = id;;
  this.name = name;
  ....
}

2022-06-20 00:45 UTC, dchickabasapa commented on portfolio/src/main/java/com/google/sps/servlets/DeleteContactServlet.java
> +  public void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
Delete should be a doDelete rather than a doPost.

2022-06-22 22:28 UTC, arnavss2 commented
I have the empty file tailwind.config.js because it is required for using IntelliSense in VSCode.

2022-06-23 06:09 UTC, dchickabasapa approved these changes

2022-06-23 06:09 UTC, merged